"""aa

Revision ID: 08210e949047
Revises: b3325003719f
Create Date: 2017-12-14 11:14:04.360344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08210e949047'
down_revision = 'b3325003719f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ban', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ban')
    # ### end Alembic commands ###
