"""aa

Revision ID: 1b05f6160261
Revises: 9745918c5fb2
Create Date: 2017-12-06 17:09:37.448662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b05f6160261'
down_revision = '9745918c5fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('the_id', sa.Integer(), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_comment_id'), 'messages', ['comment_id'], unique=False)
    op.create_index(op.f('ix_messages_from_id'), 'messages', ['from_id'], unique=False)
    op.create_index(op.f('ix_messages_post_id'), 'messages', ['post_id'], unique=False)
    op.create_index(op.f('ix_messages_the_id'), 'messages', ['the_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_the_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_post_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_comment_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
