"""empty message

Revision ID: 1bec58c64a1e
Revises: dbf4542f590e
Create Date: 2018-01-15 14:47:25.128679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bec58c64a1e'
down_revision = 'dbf4542f590e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tag_name'), 'tags', ['tag_name'], unique=False)
    op.create_table('posttag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tags_id')
    )
    op.drop_index('ix_posts_tags', table_name='posts')
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_posts_tags', 'posts', ['tags'], unique=False)
    op.drop_table('posttag')
    op.drop_index(op.f('ix_tags_tag_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
