"""aa

Revision ID: 21f3d3834805
Revises: df8931563210
Create Date: 2017-12-07 11:32:06.345524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f3d3834805'
down_revision = 'df8931563210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('post_author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_post_author_id'), 'messages', ['post_author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_post_author_id'), table_name='messages')
    op.drop_column('messages', 'post_author_id')
    # ### end Alembic commands ###
