"""aa

Revision ID: 2aff952d0a8e
Revises: e1f6bee8e074
Create Date: 2017-12-13 09:56:15.979133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aff952d0a8e'
down_revision = 'e1f6bee8e074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    # ### end Alembic commands ###
