"""aa

Revision ID: 3670bdd507d1
Revises: e38a5cf34213
Create Date: 2017-12-08 11:46:00.886071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3670bdd507d1'
down_revision = 'e38a5cf34213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('adopt', sa.Boolean(), nullable=True))
    op.add_column('answers', sa.Column('author', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answers_author'), 'answers', ['author'], unique=False)
    op.drop_index('ix_answers_a_id', table_name='answers')
    op.drop_column('answers', 'read')
    op.drop_column('answers', 'a_id')
    op.add_column('questions', sa.Column('answer', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('reply', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'reply')
    op.drop_column('questions', 'answer')
    op.add_column('answers', sa.Column('a_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_answers_a_id', 'answers', ['a_id'], unique=False)
    op.drop_index(op.f('ix_answers_author'), table_name='answers')
    op.drop_column('answers', 'author')
    op.drop_column('answers', 'adopt')
    # ### end Alembic commands ###
