"""add topic img

Revision ID: 3d8c275eacd3
Revises: fd47ffe444bb
Create Date: 2017-11-27 21:33:00.466557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8c275eacd3'
down_revision = 'fd47ffe444bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('img', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'img')
    # ### end Alembic commands ###
