"""aa

Revision ID: 46fb583e244b
Revises: 3670bdd507d1
Create Date: 2017-12-08 15:32:09.630645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fb583e244b'
down_revision = '3670bdd507d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('q_author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answers_q_author_id'), 'answers', ['q_author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_q_author_id'), table_name='answers')
    op.drop_column('answers', 'q_author_id')
    # ### end Alembic commands ###
