"""..

Revision ID: 4a42cc00682d
Revises: 9698e6b6fd82
Create Date: 2017-12-05 00:15:59.414991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a42cc00682d'
down_revision = '9698e6b6fd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('noread_messages', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_noread_messages'), 'users', ['noread_messages'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_noread_messages'), table_name='users')
    op.drop_column('users', 'noread_messages')
    # ### end Alembic commands ###
