"""aa

Revision ID: 4bb4a472b939
Revises: 2397517a19d3
Create Date: 2017-12-13 10:52:36.089317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb4a472b939'
down_revision = '2397517a19d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'topicfollows', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topicfollows', type_='foreignkey')
    # ### end Alembic commands ###
