"""aa

Revision ID: 59752826951c
Revises: 46fb583e244b
Create Date: 2017-12-08 15:37:37.696507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59752826951c'
down_revision = '46fb583e244b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('q_author_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('q_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_q_author_id'), 'messages', ['q_author_id'], unique=False)
    op.create_index(op.f('ix_messages_q_id'), 'messages', ['q_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_q_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_q_author_id'), table_name='messages')
    op.drop_column('messages', 'q_id')
    op.drop_column('messages', 'q_author_id')
    # ### end Alembic commands ###
