"""ccomments

Revision ID: 702d1c27ee22
Revises: b4f2a7ba028b
Create Date: 2017-12-04 19:32:04.771510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702d1c27ee22'
down_revision = 'b4f2a7ba028b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_comment_id'), 'comment', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_comment_id'), table_name='comment')
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###
