"""add topic clink

Revision ID: 8e0ad0a02066
Revises: 3d8c275eacd3
Create Date: 2017-11-28 15:49:06.210211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0ad0a02066'
down_revision = '3d8c275eacd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('clink', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'timestamp')
    op.drop_column('topics', 'clink')
    # ### end Alembic commands ###
