"""..

Revision ID: 9698e6b6fd82
Revises: 6c46bad534f8
Create Date: 2017-12-04 21:54:00.576268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9698e6b6fd82'
down_revision = '6c46bad534f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'body_html')
    # ### end Alembic commands ###
