"""q&a

Revision ID: 9745918c5fb2
Revises: 4a42cc00682d
Create Date: 2017-12-06 16:24:16.194711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9745918c5fb2'
down_revision = '4a42cc00682d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_id', sa.Integer(), nullable=True),
    sa.Column('a_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_a_id'), 'answers', ['a_id'], unique=False)
    op.create_index(op.f('ix_answers_q_id'), 'answers', ['q_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('clink', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_author'), 'questions', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_author'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_answers_q_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_a_id'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
