"""aa

Revision ID: b3325003719f
Revises: b548216886b7
Create Date: 2017-12-14 10:54:30.473808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3325003719f'
down_revision = 'b548216886b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban')
    # ### end Alembic commands ###
