"""aa

Revision ID: b548216886b7
Revises: b99effab5f95
Create Date: 2017-12-13 16:49:25.513855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b548216886b7'
down_revision = 'b99effab5f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('administrator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'administrator')
    # ### end Alembic commands ###
