"""aa

Revision ID: bb5c114e21e8
Revises: dc48e4410a33
Create Date: 2017-12-07 09:59:18.696548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5c114e21e8'
down_revision = 'dc48e4410a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###
