"""..

Revision ID: dbf4542f590e
Revises: 8b16a7c8e2cd
Create Date: 2018-01-13 11:57:39.721703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf4542f590e'
down_revision = '8b16a7c8e2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_posts_tags'), 'posts', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_tags'), table_name='posts')
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
