"""aa

Revision ID: df8931563210
Revises: bb5c114e21e8
Create Date: 2017-12-07 10:02:17.719694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8931563210'
down_revision = 'bb5c114e21e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_body_id'), 'messages', ['body_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_body_id'), table_name='messages')
    op.drop_column('messages', 'body_id')
    # ### end Alembic commands ###
