"""aa

Revision ID: e1f6bee8e074
Revises: 59752826951c
Create Date: 2017-12-09 14:24:35.691219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f6bee8e074'
down_revision = '59752826951c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('app', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('opp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'opp')
    op.drop_column('answers', 'app')
    # ### end Alembic commands ###
