"""aa

Revision ID: e38a5cf34213
Revises: 21f3d3834805
Create Date: 2017-12-08 11:16:28.907750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38a5cf34213'
down_revision = '21f3d3834805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'body_html')
    op.drop_column('questions', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('body_html', mysql.TEXT(), nullable=True))
    op.add_column('answers', sa.Column('body_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
