"""..

Revision ID: e7e9c98aad8d
Revises: 702d1c27ee22
Create Date: 2017-12-04 19:45:06.586802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e9c98aad8d'
down_revision = '702d1c27ee22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'read')
    # ### end Alembic commands ###
