"""post

Revision ID: fb3497310380
Revises: 8e0ad0a02066
Create Date: 2017-11-28 16:21:22.815160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3497310380'
down_revision = '8e0ad0a02066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('tpoic', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('clink', sa.Integer(), nullable=True),
    sa.Column('head', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author'), 'posts', ['author'], unique=False)
    op.create_index(op.f('ix_posts_tpoic'), 'posts', ['tpoic'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_tpoic'), table_name='posts')
    op.drop_index(op.f('ix_posts_author'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
