"""new pc

Revision ID: fd47ffe444bb
Revises: 3dec9670539f
Create Date: 2017-11-26 10:29:54.495590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd47ffe444bb'
down_revision = '3dec9670539f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_topic'), 'topics', ['topic'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_topic'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
